import { Inter } from 'next/font/google'
import './globals.css'


//components
import Navbar from './components/Navbar'




const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quill',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='min-h-full'>
      <body className={inter.className}>
        
        {children}
      </body>
    </html>
  )
}
